from file.utils import generate_filename_by_model, generate_time_based_filename, generate_uuid4_filename

# 測試函數
def test_filename_generators():
    
    # 測試 generate_filename_by_model
    model_filename = generate_filename_by_model()
    print(f"Filename generated by model: {model_filename}")
    
    # 測試 generate_uuid4_filename
    uuid_filename = generate_uuid4_filename()
    print(f"Filename generated by UUID4: {uuid_filename}")
    
    # 測試 generate_time_based_filename
    time_filename = generate_time_based_filename()
    print(f"Filename generated by timestamp: {time_filename}")


# 執行測試
if __name__ == "__main__":
    test_filename_generators()
